Update the invocation of sort() for py3
The new way is to use key= instead of positional arguments.
The old way failed with:
 TypeError: an integer is required (got type function)